name: CI

on: [push, pull_request]

jobs:
  test:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7"]

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@16930e6
        with:
          auto-update-conda: true
          mamba-version: "*"
          miniconda-version: latest
          activate-environment: dask-xgboost-test
          environment-file: ci/environment-${{ matrix.python-version }}.yaml

      - name: Install
        shell: bash -l {0}
        run: pip install --no-deps -e .

      - name: List installed packages
        shell: bash -l {0}
        run: conda list

      - name: Run flake8
        shell: bash -l {0}
        run: flake8 dask_xgboost

      - name: Run black
        shell: bash -l {0}
        run: black --check dask_xgboost

      - name: Run Tests
        shell: bash -l {0}
        run: pytest -v -s dask_xgboost
